# Inserts screenshot blocks after anchor paragraphs. Each entry: (de_anchor, en_anchor, [(img, de_caption, en_caption)])
P = [
("stellst du dagegen direkt in diesem Training ein.", "is set up\ndirectly inside that training.",
 [("home", "Die Startseite", "The home screen"),
  ("freemodes", "Freie Modi: fünf Kacheln", "Free modes: five tiles")]),
("Lektionen gibt es deshalb nur sehr wenige davon.", "very few of them.",
 [("hear_start", "Startansicht von Hören: Zeichenvorrat, Inhalt, Koch-Lektion, schwache Zeichen, Abstand und Tempo", "Listen start view: character set, content, Koch lesson, weak characters, spacing and speed")]),
("[Einzelzeichen üben](#einzelzeichen-üben)).", "[Practicing a single character](#practicing-a-single-character)).",
 [("char_sheet", "Ein Koch-Zeichen antippen: Kachel mit dem Morsecode", "Tapping a Koch character: tile with its Morse code")]),
("dann geht es weiter.", "it, then moves on.",
 [("hear_type", "Tippen: die Tastatur, nur die Zeichen der Lektion sind aktiv", "Typing: the keyboard, only the lesson's characters are active"),
  ("hear_type_retry", "Falsch: das Wort kommt noch einmal, Versuch 2 von 2", "Wrong: the word plays again, attempt 2 of 2")]),
("zeigt die gewohnte Ergebnisseite.", "usual result page.",
 [("hear_type_sent", "Gesendet nach einem getippten Block: Fehler des ersten Versuchs markiert, darunter deine Eingaben", "Sent after a typed block: first-attempt errors marked, your input below")]),
("Ergebnisse gespeichert und die Ergebnisseite erscheint.", "and the result page appears.",
 [("hear_sending", "Während des Blocks: nur Fortschritt, kein Text", "During the block: progress only, no text"),
  ("hear_revealed", "Aufgedeckt: Gruppen mit Fehlern sind rot", "Revealed: groups with errors are red"),
  ("hear_mark", "Eine Gruppe geöffnet: falsche Zeichen antippen", "One group opened: tap the wrong characters")]),
("keinen neuen Block.", "block.\n\nHow the app",
 [("hear_result", "Ergebnisseite mit Trefferquote, Abstand, schwachen Zeichen und Fortschrittsanzeige", "Result page with accuracy, spacing, weak characters and progress card"),
  ("hear_weak", "Ein schwaches Zeichen ausgenommen (durchgestrichen)", "A weak character excluded (struck through)")]),
("Werte in **fett** sind\ndie Voreinstellungen.", "Values in **bold** are\nthe defaults.",
 [("hear_sheet1", "⚙-Blatt: Koch-Reihenfolge und Übungsset", "⚙ sheet: Koch sequence and practice set"),
  ("hear_sheet2", "⚙-Blatt: Abstände, Wortauswahl, Ablauf", "⚙ sheet: Spacing, Word selection, Flow")]),
("[Einstellungen des adaptiven Modus](#einstellungen-des-adaptiven-modus)\nbeschrieben.", "[Adaptive mode settings](#adaptive-mode-settings).",
 [("hear_sheet4", "⚙-Blatt: Adaptiver Modus", "⚙ sheet: Adaptive mode")]),
("Unten liegen die Dit-/Dah-Tasten bzw. die Handtaste und **Start**.", "At the bottom are the dit/dah keys or the straight key, and **Start**.",
 [("echo_start", "Startansicht von Geben", "Send start view"),
  ("echo_answer", "Während der Antwort: Vorgabe (Vorgabe = Beides), Versuch und Tempo", "While answering: prompt (Prompt = Both), attempt and speed")]),
("übernimmt die angehakten Vorschläge ohne Verstärkung und kehrt zur\nStartansicht zurück.", "suggestions without a boost and returns to the start view.",
 [("echo_result", "Ergebnisseite: Aufteilung, Verwechslungen, schwache Zeichen, erste Versuche", "Result page: breakdown, mix-ups, weak characters, first attempts"),
  ("echo_result2", "Ein Vorschlag (hier: Gebetempo erhöhen), angehakt", "A suggestion (here: raise the sending speed), ticked")]),
("Geben zu kommen, etwa zum Einschleifen neuer Zeichen.", "for example to drill new characters.",
 [("echo_sheet", "⚙-Blatt von Geben: Abschnitt Echo Trainer", "Send ⚙ sheet: the Echo Trainer section")]),
("Das lässt\nsich nicht rückgängig machen.", "This cannot be undone.",
 [("hear_stats", "Statistik Hören: Versuche, Trefferquote, bereit", "Listen statistics: attempts, accuracy, ready"),
  ("echo_stats", "Statistik Geben mit häufigen Verwechslungen", "Send statistics with common mix-ups")]),
("tastest: CW Keyer, Geben, WiFi Trx, QSO Bot und Spiele.", "Send, WiFi Trx, QSO Bot and the games.",
 [("keyer", "CW Keyer mit dekodiertem Text", "CW Keyer with decoded text")]),
("aktuelle Dit- und Dah-Länge.", "dah length as it goes.",
 [("decoder", "CW-Decoder beim Zuhören, mit Pegelanzeige", "CW Decoder listening, with level meter"),
  ("decoder_sheet", "Einstellungen des Decoders", "Decoder settings")]),
("WiFi Trx funktioniert nur, solange die App im Vordergrund ist.", "WiFi Trx only works while the app is in the foreground.",
 [("wifi", "WiFi Trx mit Dienst, Log und Eingabefeld", "WiFi Trx with service, log and text field")]),
("Jede Verbindung läuft mit einem neuen, realistischen Rufzeichen des Bots.", "Each contact uses a new, realistic call sign for the bot.",
 [("qso", "Ein QSO mit dem Bot, Antwort per Texteingabe", "A QSO with the bot, answered with the text field")]),
("**Lange auf das Log drücken** leert\nes nach einer Rückfrage.", "**Long-press the log** to clear it after a\nconfirmation.",
 [("qso_sheet", "Einstellungen des QSO Bots", "QSO Bot settings")]),
("eine kurze Spielanleitung.", "short rules before you start.",
 [("games", "Die Spiele", "The games")]),
("sagt dir die App, welche Lektion nötig ist.", "app tells you which lesson you need.",
 [("morsel_lobby", "Morsel vor dem Start", "Morsel before the start")]),
("Die Ergebnisse kommen in eine Bestenliste.", "Results go into a high score list.",
 [("inv_lobby", "Morse Invaders vor dem Start", "Morse Invaders before the start"),
  ("inv_game", "Morse Invaders im Spiel", "Morse Invaders in play")]),
("Die Bestenliste wird je Modus geführt.", "The high score list is kept per mode.",
 [("mc_lobby", "Memory Chain vor dem Start", "Memory Chain before the start")]),
("eigenen Spielstände bleiben erhalten).", "own saved games are kept).",
 [("adv_select", "Auswahl der drei Teile", "Choosing one of the three parts")]),
("Nimmt den letzten Befehl zurück (bis zu 20) |", "Takes back the last command (up to 20) |",
 [("adv_game", "Spielbildschirm mit Touch-Keyer", "Game screen with touch keyer")]),
("verschiedenen Zeiten.", "different times.",
 [("adv_map", "Karte: Besucht", "Map: Visited"),
  ("adv_map_warn", "Nachfrage vor der ganzen Karte", "Confirmation before the whole map"),
  ("adv_map_whole", "Karte: Ganze Karte", "Map: Whole map")]),
("`TAKE LAMP. N`.", "`TAKE LAMP. N`.",
 [("adv_help", "Befehlsübersicht, unten „Worum es geht“", "Command overview, \"What it's about\" at the bottom")]),
("**Immer lang** = VERBOSE.", "**Verbose** = VERBOSE.",
 [("adv_settings", "Einstellungen: Tempo & Abstand, Eingabe", "Settings: speed & spacing, input"),
  ("adv_settings2", "Einstellungen: CW-Umfang, Text zeigen, Räume, Karte", "Settings: played in CW, show text, rooms, map")]),
("(das Spiel fragt nach).", "(the game asks).",
 [("adv_saves", "Spielstände eines Teils", "Saved games of one part")]),
("Mit **Zurück** verlässt du die Seite.", "**Back** leaves the page.",
 [("char_practice", "Üben: ein Zeichen, nachgegeben und richtig", "Practice: a character, keyed back correctly")]),
("steht im ⚙-Blatt des jeweiligen Trainings.", "that training's ⚙ sheet.",
 [("settings1", "Einstellungen: Darstellung, Allgemein, Keyer", "Settings: Appearance, General, Keyer"),
  ("settings2", "Audioausgabe und Rufzeichen", "Audio output and call signs"),
  ("settings3", "vband Morse Key, Key-Events, Info", "vband Morse Key, key events, Info")]),
]

# --- v1.3.0 additions ---------------------------------------------------
P += [
("Anhören** – spielt das Zeichen dreimal ab, mit dem Tempo dieses Trainings.", "**Listen** – plays the character three times, at this training's speed.",
 [("hear_char_detail", "Detailansicht in Hören: Kurve pro Woche, Freischaltung", "Detail view in Listen: weekly curve, unlock"),
  ("echo_char_detail", "Detailansicht in Geben: letzte 30 Versuche, Kurve, Verwechslungen", "Detail view in Send: last 30 attempts, curve, mix-ups")]),
("Tippe auf ein Zeichen, um seine\n  Detailansicht zu öffnen.", "Tap\n  a character to open its detail view.",
 [("hear_progress", "Reiter Verlauf (Hören): Quote, Tempo und Übungstage über 12 Wochen", "Progress tab (Listen): hit rate, speed and days practised over 12 weeks"),
  ("hear_progress2", "Darunter die Heatmap: alle Zeichen, Woche für Woche", "Below it the heatmap: all characters, week by week"),
  ("echo_progress", "Reiter Verlauf (Geben)", "Progress tab (Send)")]),
("bei jedem Text, wie viel du schon gehört hast.", "have heard.",
 [("own_library", "Eigene Texte: die Bibliothek", "Own texts: the library"),
  ("own_player", "Ein Text wird gespielt (Anzeige: Nach Abspielen)", "A text playing (display: After playing)")]),
("an, solange du in einem Text bist.", "a text.",
 [("own_sheet", "⚙-Blatt der Eigenen Texte", "⚙ sheet of Own texts")]),
("eigenes Training sind.", "not a training of its own.",
 [("res_hub", "Lernressourcen: Morse-Baum, Zeichentabelle, Links", "Learning resources: Morse tree, character chart, links")]),
("Baum steht der Code noch einmal als Punkte und Striche.", "dits and dahs.",
 [("tree_letters", "Morse-Baum: Weg zum Q leuchtet auf", "Morse tree: the path to Q lights up"),
  ("tree_deep", "Mit Ziffern und Zeichen: der Baum scrollt seitwärts", "With digits and signs: the tree scrolls sideways")]),
("bleibt im Hochformat.", "stays in portrait.",
 [("tree_letters_land", "Querformat: Buchstaben", "Landscape: letters"),
  ("tree_deep_land", "Querformat mit Ziffern und Zeichen: der ganze Baum passt", "Landscape with digits and signs: the whole tree fits")], "shots wide"),
("Die Tonhöhe stellst du unter Einstellungen → Allgemein ein.", "Set the pitch under Settings → General.",
 [("chart", "Zeichentabelle: ein Zeichen leuchtet beim Abspielen", "Character chart: a character lights up while it plays")]),
("die App verlinkt sie nur und zeigt nichts von deren Inhalt.", "the app only links to them and shows nothing of their content.",
 [("links", "Links zu Kursen und Übungsseiten", "Links to courses and practice sites")]),
]
import re, os
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
for lang, ai in (('de', 0), ('en', 1)):
    f = f'manual_{lang}.md'; s = open(f).read()
    s = re.sub(r'\n\n::: \{\.shots[^}]*\}\n.*?\n:::', '', s, flags=re.S)   # idempotent
    for entry in P:
        anchor, imgs = entry[ai], entry[2]
        i = s.find(anchor); assert i >= 0, (lang, anchor)
        j = s.find('\n\n', i + len(anchor) - 1)
        if j < 0: j = len(s)
        cls = entry[3] if len(entry) > 3 else {1: 'shots one', 3: 'shots three'}.get(len(imgs), 'shots')
        block = f'\n\n::: {{.{cls.replace(" ", " .")}}}\n' + '\n\n'.join(
            f'![{c[1 + ai]}](img/{lang}/{c[0]}.png)' for c in imgs) + '\n:::'
        s = s[:j] + block + s[j:]
    open(f, 'w').write(s)
print('ok')
