import re
bad=r"""(?:t[oö]t|tod|sterb|stirb|starb|gestorb|leiche|mord|mörd|ermord|umbring|töt|toet|kill|blut|bluten|schie[sß]|schuss|schoss|gewehr|pistole|waffe|bombe|explo|messer|stech|stach|schwert|krieg|kämpf|kampf|kaempf|angriff|angreif|feind|armee|soldat|milit|schlag|schlug|prügel|treten|trat\b|verletz|wunde|schmerz|folter|opfer|gewalt|brutal|grausam|hass|hasse|wut|wüt|böse|teufel|dämon|hölle|fluch|verflucht|töte|hinricht|erschie|erhäng|hängen|erwürg|ersticken|vergift|gift|ertrink|selbstmord|suizid|terror|geisel|entführ|räuber|raub|einbruch|dieb|stehl|stahl|gestohlen|betrug|betrüg|lüg|luege|lügner|lüge|verbrech|krimin|straf|verhaft|polizei|bulle|cop\b|gefängnis|knast|gericht|richter|anwalt|zeuge|beweis|schuld|verdächt|verdacht|detektiv|mafia|gang\b|bande|droge|kokain|heroin|haschisch|gras\b|kiffen|bier|wein\b|schnaps|wodka|whisk|alkohol|betrunken|besoffen|saufen|sauf|rausch|zigarette|rauch|tabak|spritze|tablette|pille|medikament|spielen?\b.*kasino|kasino|poker|wette|wetten|glücksspiel|krebs|krank|seuche|virus|tumor|leiden|schrei|panik|gefahr|angst|furcht|grab|beerdig|begräb|sarg|friedhof|geist\b|gespenst|monster|hexe|alptraum|albtraum|katastrophe|unfall|absturz|zerstör|vernicht|ruine|brand|feuer|verbrenn|sklave|sexu|sex\b|sexy|nackt|hure|nutte|ficken|fick|scheiß|scheiss|scheisse|arsch|schwanz|titten|möse|wichs|schwul|neger|idiot|dumm|blöd|trottel|depp|arschloch|verdammt|mist\b|kack|pisse|pinkel|kotz|scheu\b|krüppel|behindert|nazi|hitler|jude|juden|hakenkreuz|holocaust|gestapo|konzentration|ss\b)"""
BAD=re.compile(bad)
inter=set("oh ah ach äh ähm hm hmm mm uh um huh ha haha hehe heh hey hi ho hallo ok okay yeah yes no na nana tja pff pfff puh uff ups hä he ey eh aha oha ooh mmm igitt bäh buh bravo gut uhr sir mr mrs ms dr mrs lady miss mister hey wow gee cool sorry please thanks the and you not but for that with this are was what have your from they will can one just all get know like there out about want think see come now here don didn doesn isn wasn aren couldn wouldn shouldn won let him her them then than when who how why where which were would could should been being said say way even also its still too any may much our their time good very over such only into other more some two see make well back after first take say man life day look right going".split())
names=set("""hans peter michael thomas andreas stefan markus martin frank klaus jürgen uwe jens kurt karl franz josef josef johann anna maria sarah julia lisa laura lena emma sophie hannah lea mia nina eva ute petra sabine monika karin susanne claudia christine gabi heidi ingrid erika helga inge ursula brigitte renate angelika birgit andrea nicole jessica jennifer vanessa jana sandra tanja kerstin silke anja daniela melanie stefanie katharina elisabeth margarete charlotte charlie jack john james david tom tim max paul felix jonas leon luca ben lukas tobias daniel dennis kevin jan jens florian sven ralf rainer dieter horst günter werner walter gerhard wolfgang helmut manfred herbert bernd rolf heinz otto emil anton albert alfred arthur ludwig fritz hugo willi egon erwin rudi ernst fred georg harry henry jim joe mike nick paul rob sam steve tony bob bill billy tommy johnny jimmy eddie danny larry jerry gary terry kenny benny dave ted ray roy ron don ken lee lou stan jay jake jason josh justin kyle ryan sean adam alex alan andy ben brian chris colin craig dean doug eric evan gavin glen greg hank ian jeff jeremy joel keith kurt lance luke marc matt neil noah owen pat phil rick ross russ scott seth todd troy walt wes zach berlin münchen hamburg köln wien paris london rom amerika europa deutschland österreich frankreich england russland china japan italien spanien afrika asien texas california new york washington amerikaner deutsche deutscher deutsches englisch deutsch französisch amerikanisch russisch""".split())
en={};ten=0
for l in open('fw/en_50k.txt'):
    w,c=l.split(); en[w]=int(c); ten+=int(c)
tde=sum(int(l.split()[1]) for l in open('fw/de_50k.txt'))
extra=set('katie shane daisy williams hollywood alexander bud colt stanley lewis margaret christian connor rebecca hogan tracy clay kent chase gus lex logan kirk inspector camp rita lincoln audrey quinn ann murphy julian stone baron herman liz wade nigger versaut beschissen knarre handschellen bewaffnet beute treffer illegal alibi bestie knurrt reverend zauberer admiral pilot sinnlos widerlich ekelhaft eklig papi clown sonny sydney steele diane moskau homer dylan peggy manny archer meg holly katherine lana shaw grey russell sherlock castle mitchell palmer lydia hanna duke mona vic marcel finn ronnie samantha kanone panzer angeklagt versager psychiater gefesselt geschworen biest symptome spinner marine avenue cowboy data hurra oje bargeld richard jane clark george lily alice robin pete simon joey jenny lois chief officer doc san van fair ner nem mon jawohl guck polizist polizisten umgebracht angegriffen verfolgt verfolgen gefangen entkommen mission respekt sergeant lieutenant commander captain bobby chuck rachel kate amanda roger carter emily louis dan roy robert charles claire mary monsieur madame colonel major al la de ma mama mami daddy opa oma weiss schlampe mistkerl fuck maul hintern schwein quatsch irre kugel rache unschuldig erschossen geschossen schande hals jesus lord'.split())
dropped=[]
rows=[]
for l in open('de_spell.txt'):
    w,c=l.split(); c=int(c)
    if w in inter or w in names: continue
    if BAD.search(w) or w in extra: continue
    if w in en and (en[w]/ten) > 4*(c/tde): dropped.append(w); continue
    if len(w)==2 and w not in set("zu in er es du ja ob so um an am im da wo ab je ihr".split()): continue
    rows.append((w,c))
rows=rows[:2500]
open('de_candidate.txt','w').write(''.join(f'{w} {c}\n' for w,c in rows))
print(len(rows),rows[-1])

print('EN-dropped',len(dropped),' '.join(dropped[:150]))
